apiVersion: v1
kind: Service
metadata:
  name: Testproject666
spec:
  selector:
    app: Testproject666
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
