apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Testproject666-project
  namespace: argocd
spec:
  description: Project for Testproject666
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'